version: '3.9'
services:
  # MySQL server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "tutorials"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  # API Server
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    depends_on:
      mysql:
        condition: service_started
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./api:/app
    restart: on-failure
    environment:
      NODE_ENV: development
      MYSQL_HOSTNAME: mysql
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DB_NAME: "tutorials"